name: build our image

on:
  push:
    branches: master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v2
      - name: install buildx
        id: buildx
        #uses: crazy-max/ghaction-docker-buildx@v1
        uses: crazy-max/ghaction-docker-buildx@v3.3.1
        with:
          version: latest
      - name: build the image
        run: docker buildx build --tag slaesh/mosquitto-w-timestamps:latest --platform linux/amd64,linux/arm/v7,linux/arm64 ./docker/local
